# Generated by Django 5.0.14 on 2026-02-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.shop')),
            ],
            options={
                'unique_together': {('shop', 'name', 'set_name', 'card_number', 'variant', 'language')},
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('grading', 'Sent for Grading'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.card')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='accounts.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment', 'Manual Adjustment'), ('grading_out', 'Sent for Grading'), ('grading_in', 'Returned from Grading'), ('reserve', 'Reserved'), ('unreserve', 'Unreserved'), ('import', 'CSV Import')], max_length=20)),
                ('quantity_delta', models.IntegerField()),
                ('resulting_quantity', models.PositiveIntegerField()),
                ('provider_event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.inventorylot')),
            ],
        ),
    ]
