# Generated by Django 5.0.14 on 2026-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
