# Generated by Django 5.0.14 on 2026-02-23 18:15

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ebay', 'eBay')], default='ebay', max_length=50)),
                ('credentials', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_poll_cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.shop')),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('dead', 'Dead')], default='queued', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('retries', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='channels.channelintegration')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_listing_id', models.CharField(max_length=255)),
                ('external_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('listed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listed_quantity', models.IntegerField(default=0)),
                ('sync_state', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error'), ('delisted', 'Delisted')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='channels.channelintegration')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='inventory.inventorylot')),
            ],
            options={
                'unique_together': {('integration', 'external_listing_id')},
            },
        ),
    ]
