# Generated by Django 5.0.14 on 2026-02-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_quantity', models.IntegerField(blank=True, null=True)),
                ('channel_quantity', models.IntegerField(blank=True, null=True)),
                ('external_listing_id', models.CharField(blank=True, max_length=255)),
                ('external_sku', models.CharField(blank=True, max_length=255)),
                ('external_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('push_internal', 'Push Internal to Channel'), ('pull_channel', 'Pull Channel to Internal'), ('ignore', 'Ignored')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='channels.channelintegration')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='channels.channellisting')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='inventory.inventorylot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
